apiVersion: v1
kind: Service
metadata:
  name: backend-user
  labels:
    service: backend-user
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    service: backend-user